title: Lernwerkstatt
lang: de
# Bei einem Repository namens <name>.github.io bleibt baseurl leer.
# Bei einem anderen Repository-Namen hier "/<repository-name>" eintragen.
baseurl: "/drehtisch"

collections:
  aufgaben:
    output: true

defaults:
  - scope:
      type: aufgaben
    values:
      layout: aufgabe

exclude:
  - README.md
